### ISSUE TITLE
期待代码开源

### ISSUE THREAD

**Issue by Aliang-CN** [Flash-321/ARLDM#1]
这是一个令人振奋的结果，期待代码开源！

**Comment by xichenpan** [comment]
Hi, we are happy to announce that we already finalize the code release review of Alibaba Group. In the following weeks, we will immigrate the codebase to Pytorch Lightning and HDF5. Feel free to reach out about further questions~

**Comment by Aliang-CN** [comment]
> Hi, we are happy to announce that we already finalize the code release review of Alibaba Group. In the following weeks, we will immigrate the codebase to Pytorch Lightning and HDF5. Feel free to reach out about further questions~

thanks ！！！

**Comment by xichenpan** [comment]
> > Hi, we are happy to announce that we already finalize the code release review of Alibaba Group. In the following weeks, we will immigrate the codebase to Pytorch Lightning and HDF5. Feel free to reach out about further questions~
> 
> thanks ！！！

Hi, we have already immigrated the codebase to Pytorch Lightning and HDF5 (also fixed some bugs), you may access this new codebase now!

**Comment by Aliang-CN** [comment]
> > > Hi, we are happy to announce that we already finalize the code release review of Alibaba Group. In the following weeks, we will immigrate the codebase to Pytorch Lightning and HDF5. Feel free to reach out about further questions~
> > 
> > 
> > thanks ！！！
> 
> Hi, we have already immigrated the codebase to Pytorch Lightning and HDF5 (also fixed some bugs), you may access this new codebase now!

好的，多谢大佬，我最近也在关注AIGC在漫画上的应用。非常期待大佬的工作可以推动这个领域往前走一大步
