### ISSUE TITLE
dataset for VIST

### ISSUE THREAD

**Issue by kriskrisliu** [Flash-321/ARLDM#3]
Thanks for opensource!
I'm focusing on reproducing this work and notice that datasets include both VIST-SIS and VIST-DII. However the download script (vist_img_download.py) only suggest to download DII, while vist_hdf5.py only converts SIS.

My question is how to organize VIST-SIS/DII for training in detail.

**Comment by xichenpan** [comment]
Hi, vist-dii and vist-sis shares the same images but different captions. The `vist_img_download.py` file use only dii jsons, but it downloads the needed images for both vist-sis and vist-dii. `vist_hdf5.py` file also save both sis and dii captions into one hdf5 file, you can access them through `sis` and `dii` keys, as shwon in https://github.com/Flash-321/ARLDM/tree/main/data_script#L97-L100.

**Comment by kriskrisliu** [comment]
Cool!
